 <!-- Js Plugins -->
 <script src="{{ url('frontend/js/jquery-3.3.1.min.js') }}"></script>
 <script src="{{ url('frontend/js/bootstrap.min.js') }}"></script>
 <script src="{{ url('frontend/js/jquery-ui.min.js') }}"></script>
 <script src="{{ url('frontend/js/jquery.countdown.min.js') }}"></script>
 <script src="{{ url('frontend/js/jquery.nice-select.min.js') }}"></script>
 <script src="{{ url('frontend/js/jquery.zoom.min.js') }}"></script>
 <script src="{{ url('frontend/js/jquery.dd.min.js') }}"></script>
 <script src="{{ url('frontend/js/jquery.slicknav.js') }}"></script>
 <script src="{{ url('frontend/js/owl.carousel.min.js') }}"></script>
 <script src="{{ url('frontend/js/main.js') }}"></script>
